name: infinit_test_esteban
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: '>3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.2.2
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_gemini: ^2.0.3
  json_annotation: ^4.8.1
  package_info_plus: ^6.0.0
  freezed_annotation: ^2.4.1
  flutter_markdown: ^0.6.22+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  json_serializable: ^6.7.1
  freezed: ^2.5.0

flutter:
  uses-material-design: true
